novoda/spikes

- landing-strip/build.gradle
- landing-strip/core/build.gradle
- landing-strip/core/src/main/java/com/novoda/landingstrip/LandingStrip.java
- landing-strip/core/src/main/java/com/novoda/landingstrip/TabsContainer.java
- landing-strip/demo/build.gradle
- landing-strip/demo/src/main/AndroidManifest.xml
- landing-strip/demo/src/main/java/com/novoda/landingstrip/FixedWidthTabActivity.java
- landing-strip/demo/src/main/java/com/novoda/landingstrip/setup/fragment/SmallDemoFragmentPagerAdapter.java
- landing-strip/demo/src/main/res/layout/activity_fixed_width_tab.xml
- landing-strip/demo/src/main/res/layout/tab_fixed_width.xml
- landing-strip/gradle/wrapper/gradle-wrapper.properties
Fixes a bug in tab layout inflation which now permits fixed width operation:
> Bug fix layout inflation using incorrect parent

- Firebase/android/app/src/main/java/com/novoda/bonfire/chat/view/MessageView.java
- Firebase/android/app/src/main/res/layout/merge_message_item_view.xml
- Firebase/android/app/src/main/res/values/colors.xml
Displays the author of the message with the date when the message was sent.
> Bonfire / Display message author and time with each message

- Firebase/android/app/src/main/AndroidManifest.xml
- Firebase/android/app/src/main/java/com/novoda/bonfire/Dependencies.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/channel/ChannelsActivity.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/channel/service/FirebaseChannelService.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/channel/view/ChannelView.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/channel/view/ChannelViewHolder.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/channel/view/ChannelsAdapter.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/channel/view/ChannelsView.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/chat/ChatActivity.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/chat/service/FirebaseChatService.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/chat/view/MessageView.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/navigation/AndroidLoginNavigator.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/navigation/AndroidNavigator.java
- Firebase/android/app/src/main/res/layout/activity_channels.xml
- Firebase/android/app/src/main/res/layout/merge_channel_item_view.xml
- Firebase/android/app/src/main/res/layout/merge_channels_view.xml
- Firebase/android/app/src/main/res/layout/merge_chat_view.xml
- Firebase/android/app/src/main/res/layout/merge_message_item_view.xml
- Firebase/android/app/src/main/res/values/dimens.xml
- Firebase/android/core/src/main/java/com/novoda/bonfire/Presenter.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/channel/data/model/Channel.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/channel/data/model/Channels.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/channel/displayer/ChannelsDisplayer.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/channel/presenter/ChannelsPresenter.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/channel/service/ChannelService.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/chat/presenter/ChatPresenter.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/chat/service/ChatService.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/login/presenter/LoginPresenter.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/navigation/Navigator.java
- Firebase/server/database.rules.json
Adds an activity that displays list of all public channels (currently only "global") and allows the user to select a channel.
| Before | After |  
| --- | --- |
| ![channels_before](https://cloud.githubusercontent.com/assets/1104656/15285219/ccfae0d4-1b4d-11e6-977b-c3969d969ce6.png) |  ![channels_after](https://cloud.githubusercontent.com/assets/1104656/15285130/5d3d2810-1b4d-11e6-9515-7cb706786f04.gif) |
Paired with
@tobiasheine
> Firebase / Display public channels in a list

- ReactNative/ReactTwitter/__tests__/core/service/oauth-helper.test.js
- ReactNative/ReactTwitter/core/service/authentication-service.js
- ReactNative/ReactTwitter/core/service/config.json
- ReactNative/ReactTwitter/core/service/oauth-helper.js
- ReactNative/ReactTwitter/core/service/twitter-requests-service.js
- ReactNative/ReactTwitter/core/views/oauth-screen.js
TL;DR;
Completed Oauth Flow
Create an AuthenticationService that provide information about the logged user
Update Debug Screen: Every time we authenticate now we store the information into the AuthenticationService so that they are persisted in the app
|iOS|Android|
|---|---|
|Part 1| Part 1|
|![1st time ios](https://cloud.githubusercontent.com/assets/797790/15252657/3ea4a61e-192f-11e6-8a75-d86889f96e80.gif) | ![0 time android](https://cloud.githubusercontent.com/assets/797790/15252675/586a6b7e-192f-11e6-867b-32e2769b12e2.gif) |
|Part 2| Part 2|
| ![2nd time ios](https://cloud.githubusercontent.com/assets/797790/15252664/4afa1c0a-192f-11e6-995c-a5cb6d2ca2e7.gif) | ![1st time android](https://cloud.githubusercontent.com/assets/797790/15252678/5cb19356-192f-11e6-866c-308747712e08.gif) |
> React/pt 68/oauth last part

- Firebase/server/database.rules.json
Updates database rules.
Paired with
@dominicfreeston and @yvettecook
> Update database rules to enforce correct channel creation

- Firebase/ios/Bonfire/Mobile/Channel/FirebaseChannelsService.swift
- Firebase/ios/Bonfire/Mobile/Chat/FirebaseChatService.swift
Updating iOS app to work with new database structure merged in #43.
> Update database references tofit with database restructure

- Firebase/server/database.rules.json
Because channel type is too generic.
> rename channel type to channel access

- Firebase/android/app/src/main/java/com/novoda/bonfire/channel/service/FirebaseChannelService.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/chat/ChatActivity.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/chat/service/FirebaseChatService.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/login/service/FirebaseLoginService.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/channel/data/model/Channel.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/channel/data/model/ChannelInfo.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/chat/presenter/ChatPresenter.java
Updates the FIrebaseChannelService to reflect the updated structure of channels and their indexes.
> Update channel service to reflect the new channel structure

- ReactNative/ReactTwitter/.flowconfig
- ReactNative/ReactTwitter/ios/ReactTwitter.xcodeproj/project.pbxproj
- ReactNative/ReactTwitter/ios/ReactTwitter/Info.plist
- ReactNative/ReactTwitter/package.json
Updated React-Native to 0.26.1. 
This version is not compatible with the latest version of React, so I have to point the package.json to a specific version.
> Updated to last version of React Native

- ReactNative/ReactTwitter/core/views/debug/debug-animation-scene.js
- ReactNative/ReactTwitter/core/views/debug/debug-screen.js
- ReactNative/ReactTwitter/core/views/main-navigator.js
- ReactNative/ReactTwitter/core/views/splash-screen.js
Created a debug screen with some sample animations and animated the logo into the splash screen. 
| iOS  | Android |
| --- | --- |
|![animations-ios](https://cloud.githubusercontent.com/assets/797790/15540226/8a3c81e0-2286-11e6-9e98-3f1a64b389f1.gif)| ![animations-android](https://cloud.githubusercontent.com/assets/797790/15540229/8dcf047c-2286-11e6-8946-3fdab2d2216c.gif)|
> React - Animations 

- ReactNative/ReactTwitter/core/views/debug/push-notifications-screen.js
- ReactNative/ReactTwitter/index.ios.js
- ReactNative/ReactTwitter/ios/ReactTwitter.xcodeproj/project.pbxproj
- ReactNative/ReactTwitter/ios/ReactTwitter/AppDelegate.m
- ReactNative/ReactTwitter/ios/ReactTwitter/Info.plist
- ReactNative/ReactTwitter/ios/ReactTwitterTests/Info.plist
Nothing really relevant to comment about this PR, I just need to bridge some event from the app to the react-native component. When a notification is received, an alert pop up.
> Push Notification iOS

- ReactNative/ReactTwitter/core/views/debug/debug-animation-scene.js
- ReactNative/ReactTwitter/core/views/debug/debug-native-component-scene.js
- ReactNative/ReactTwitter/core/views/debug/debug-screen.js
- ReactNative/ReactTwitter/core/views/debug/deep-linking.js
- ReactNative/ReactTwitter/core/views/debug/oauth-screen.js
- ReactNative/ReactTwitter/core/views/debug/push-notifications-screen.js
- ReactNative/ReactTwitter/core/views/login-screen.js
- ReactNative/ReactTwitter/core/views/main-navigator.js
- ReactNative/ReactTwitter/core/views/splash-screen.js
- ReactNative/ReactTwitter/core/views/tweetView.js
- ReactNative/ReactTwitter/core/views/tweetsList.js
- ReactNative/ReactTwitter/core/views/tweetsListItem.js
Added the debug screen for the native component, it already implement a basic ListView
Debug Screen is now a ListView easily configurable with new screens
Refactor navigator so we get rid of magic string constants
Each screen now implement static methods for the navigatorID and
> Added Debug Screen for Native Component Screen

- Firebase/android/app/src/main/java/com/novoda/bonfire/channel/view/ChannelView.java
- Firebase/android/app/src/main/res/drawable/ic_lock_black.xml
- Firebase/android/app/src/main/res/layout/merge_channel_item_view.xml
This PR adds a lock Icon to the private channels in the list.
| Before | After |
| --- | --- | 
|![beforelock](https://cloud.githubusercontent.com/assets/610924/15861898/c01b4578-2cc5-11e6-817a-5046e09128ef.png)|![afterlock](https://cloud.githubusercontent.com/assets/610924/15861899/c01ee156-2cc5-11e6-97ea-110238113a48.png)|
> Adding a lock icon to the private channels

- Firebase/android/app/src/main/java/com/novoda/bonfire/Dependencies.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/analytics/FirebaseAnalyticsAnalytics.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/channel/ChannelsActivity.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/chat/ChatActivity.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/login/LoginActivity.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/user/UsersActivity.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/welcome/WelcomeActivity.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/analytics/Analytics.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/channel/presenter/ChannelsPresenter.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/chat/presenter/ChatPresenter.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/login/presenter/LoginPresenter.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/user/presenter/UsersPresenter.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/welcome/presenter/WelcomePresenter.java
This adds a bunch of new analytics events.
Once the events show up in the console we can make some funnels.
These are some that I thought of:
```
invite_opened -> invite_accepted -> sign_up -> sign_up_success
select_content -> message_length
select_content -> manage_owners
```
> New analytics events

- Firebase/android/README.md
Adds a basic README.md file.
I was focusing on the steps that describe how to run the app with own firebase instance.
> Readme file

- Firebase/ios/Bonfire.xcodeproj/project.pbxproj
- Firebase/ios/Bonfire.xcodeproj/xcshareddata/xcschemes/Bonfire.xcscheme
- Firebase/ios/Bonfire.xcodeproj/xcshareddata/xcschemes/UITests.xcscheme
- Firebase/ios/Bonfire/Info.plist
- Firebase/ios/Bonfire/Mobile/FirebaseIdentifiers.swift
- Firebase/ios/Bonfire/Mobile/SharedServices.swift
- Firebase/ios/README.md
Not wild on the naming of FirebaseIdentifiers - open to suggestions
> Added ReadMe and configurable FirebaseIdentifiers

- Firebase/android/app/src/main/java/com/novoda/bonfire/channel/NewChannelActivity.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/channel/view/NewChannelView.java
- Firebase/android/app/src/main/res/drawable/ic_clear_white_24dp.xml
- Firebase/android/app/src/main/res/layout/merge_create_channel_view.xml
- Firebase/android/app/src/main/res/layout/toolbar_non_elelvated_layout.xml
- Firebase/android/app/src/main/res/menu/new_channel_menu.xml
- Firebase/android/app/src/main/res/values/colors.xml
- Firebase/android/app/src/main/res/values/strings.xml
- Firebase/android/core/src/main/java/com/novoda/bonfire/channel/displayer/NewChannelDisplayer.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/channel/presenter/NewChannelPresenter.java
This PR implements design specs for the Create Channel screen
| Before | After |
| --- | --- |
> Create Channel UI to specs

- Firebase/android/app/build.gradle
- Firebase/android/app/src/main/java/com/novoda/bonfire/Dependencies.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/FirebaseConfig.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/channel/ChannelsActivity.java
- Firebase/android/app/src/main/res/xml/remote_config_defaults.xml
- Firebase/android/core/src/main/java/com/novoda/bonfire/Config.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/channel/data/model/Channels.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/channel/presenter/ChannelsPresenter.java
This PR allows for remote configuration of the ordering of the Channels list.
> Add Remote config to trigger sorting of channels

- Firebase/android/app/src/main/java/com/novoda/bonfire/user/view/UsersView.java
- Firebase/android/app/src/main/res/drawable/ic_done.xml
- Firebase/android/app/src/main/res/layout/merge_user_item_view.xml
- Firebase/android/app/src/main/res/menu/users_menu.xml
- Firebase/android/app/src/main/res/values/colors.xml
This PR updates the design of the add user screen.
| Before | After
| --- | --- |
> Update designs for selected screen

- Firebase/android/app/src/main/java/com/novoda/bonfire/login/view/LoginView.java
- Firebase/android/app/src/main/res/drawable/bubble_shape_background.xml
- Firebase/android/app/src/main/res/layout/merge_login_view.xml
- Firebase/android/app/src/main/res/values/colors.xml
- Firebase/android/app/src/main/res/values/strings.xml
This PR updates the design of the login screen and adds a disclaimer about privacy.
| Before | After
| --- | --- |
> Update design for login screen

- MakeFestSimonSays/app/src/main/java/com/novoda/simonsays/game/Round.java
- MakeFestSimonSays/app/src/main/java/com/novoda/simonsays/game/RoundCreator.java
It now gets faster each round (and is quite hard!) :-)
> Makefest - speed up the game each round

- MakeFestSimonSays/app/src/main/java/com/novoda/simonsays/game/GameActivity.java
- MakeFestSimonSays/app/src/main/java/com/novoda/simonsays/game/RoundCreator.java
- MakeFestSimonSays/app/src/main/java/com/novoda/simonsays/highscores/HighscoresActivity.java
- MakeFestSimonSays/app/src/main/res/layout/game_activity.xml
- MakeFestSimonSays/app/src/main/res/layout/highscores_activity.xml
- MakeFestSimonSays/app/src/main/res/layout/main_menu_activity.xml
- MakeFestSimonSays/app/src/main/res/values/colors.xml
- MakeFestSimonSays/app/src/main/res/values/dimens.xml
- MakeFestSimonSays/app/src/main/res/values/strings.xml
- MakeFestSimonSays/app/src/main/res/values/styles.xml
Nicer UI for Main, Game and HighScore.
Also fixed some bugs with rotation and starting new activities multiple times.
Before | After
--- | ---
Colour position was changed to match this controller:
> Makefest. Nicer simon ui

- BuildPropertiesPlugin/gradle/publish.gradle
- BuildPropertiesPlugin/plugin/build.gradle
What the tin says. Follow-up would be releasing the plugin via the Novoda CI.
> BuildPropertiesPlugin: Add bintray support

- ReactNative/ReactTwitter/LICENSE.txt
> Add license to React Native spike

- slacker/README.md
Add a README on the `slacker` section.
This README is lacking a section on how to develop a custom widget. As the dashboard has been going through some changes (it's not stable/has not been "released") I felt it's still a bit early to add the section.
> Slacker README

- slacker/public/widgets/stackoverflow.js
- slacker/server/stackoverflow.js
Picks a random unanswered question and displays it.
> [Slacker] stackoverflow random question

- enews/enews-node/demo.js
- enews/enews-node/enews-fetcher.js
- enews/enews-node/package.json
- enews/enews-node/slack.js
- enews/html-generator-node/demo.js
- enews/mailer-node/enews-mailer.js
Enews wasn't being correctly parsed due to the room name having changed.
Also took the time to rewrite all of the usages so that they're more up to date with my latest javascript knowledge 😉
> Enews update ❤️

- GitHubTest/Test.md
This is a dummy PR just to see the new squash behaviour in action
> Feature/test Squash behaviour

- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/SelfDestructingMessageView.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/controller/BotControllerActivity.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/controller/Direction.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/controller/DirectionPadView.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/controller/OnDirectionPressedListener.java
- TelepresenceBot/mobile/src/main/res/layout/activity_bot_controller.xml
- TelepresenceBot/mobile/src/main/res/values/colors.xml
- TelepresenceBot/mobile/src/main/res/values/controller-styles.xml
- TelepresenceBot/mobile/src/main/res/values/styles.xml
This PR modifies the `BotControllerActivity`'s layout in order to display a view that shows which button was pressed from the `DirectionPadView`
I think its something that will come in handy when we send commands back and forth in the future. Plus it was so fun to build 😄
> Directions debug screen ← ↑ → ↓ 💥

- GitHubTest/Test.md
> Sub feature

- GitHubTest/Test.md
> Sub feature2

- GitHubTest/Test.md
> big conflict

- GitHubTest/Test.md
* hotifx
* even more
* conflicting hotfix
> Hotfix (#204)

- GitHubTest/Test.md
> Test master

- GitHubTest/Test.md
> Long running

- GitHubTest/Test.md
> Short running

- GitHubTest/Test.md
* Long running (#208)
* adding some numbers
* adding more commits
* is good
* adding new number
* Short running (#209)
* continuing four
* continuing six
> Big feature (#210)

- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/Result.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/support/Optional.java
Need to represent a result when attempting to connect to the server (bot) part of the app and vice-versa. 
Create a `Result` that uses `Optional` to represent either a success message or an error exception. This will be implemented in a follow-up PR when the `TpBotService` is added to the project.
> TpBot: Result

- GitHubTest/Test.md
> Test feature/doin stuff

- GitHubTest/Test.md
> Test feature/banana

- GitHubTest/Test.md
> Test feature/feature branch

- GitHubTest/Test.md
> New feature/ruh roh

- GitHubTest/Test.md
> New feature/times two

- GitHubTest/Test.md
> New feature/conflicts ahoy

- GitHubTest/Test.md
Two bananas, a beer and some wine (because why not)
> New feature/feature branch

- GitHubTest/Test.md
> Feature first/sub1

- GitHubTest/Test.md
> Feature first/sub2

- GitHubTest/Test.md
> Feature first/feature branch

- GitHubTest/Test.md
> Feature second/feature branch

- TelepresenceBot/core/src/main/java/com/novoda/tpbot/human/HumanPresenter.java
- TelepresenceBot/core/src/main/java/com/novoda/tpbot/human/HumanView.java
- TelepresenceBot/core/src/test/java/com/novoda/tpbot/human/HumanPresenterTest.java
- TelepresenceBot/core/src/test/java/com/novoda/tpbot/support/ObservableTest.java
`TpHuman` has a  nice `HumanTpService` and a `HumanView` interface but not a presentation layer that binds the two together.
Create the `HumanPresenter` to handle the calls to the `TpService` and accept pushes from that service to display in the UI.
> Tpbot human presenter

- monkey-runner/dependencies.gradle
- monkey-runner/plugin/src/main/groovy/com/novoda/monkey/MonkeyConfigurationPlugin.groovy
Updated command plugin version to 1.7.0
Made the necessary changes to the setup. Since we are creating new tasks for every step, it needs more now. Hopefully in the future, the command plugin will be flexible enough so that instead of creating tasks, configuring it would be enough to do this.
> [monkey-runner] Update android command plugin

- TelepresenceBot/core/src/main/java/com/novoda/tpbot/Direction.java
- TelepresenceBot/core/src/main/java/com/novoda/tpbot/human/HumanPresenter.java
- TelepresenceBot/core/src/main/java/com/novoda/tpbot/human/HumanTpService.java
- TelepresenceBot/core/src/main/java/com/novoda/tpbot/support/Observable.java
- TelepresenceBot/core/src/test/java/com/novoda/tpbot/human/HumanPresenterTest.java
- TelepresenceBot/mobile/build.gradle
- TelepresenceBot/mobile/src/main/AndroidManifest.xml
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/human/HumanActivity.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/human/HumanSocketIOTpService.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/human/SocketIOTpService.java
- TelepresenceBot/mobile/src/main/res/values/strings.xml
- TelepresenceBot/mobile/src/main/res/values/styles.xml
The `Human` part of the app does not connect with any remote server and so cannot send commands to a corresponding `Bot` app. 
Add a `SocketIO` implementation whereby the `Human` part of the app can communicate with a remote server in order to send commands.
- This part of the app does not actually send commands just yet, just establishes a connection and handles any connection errors that may occur. 
Incorrect Address | Timeout | Connected
--- | --- | ---
- Add `SocketIO` implementation to `Bot` part of the app.
- Replace the `RecyclerView` with the reusable `DebugView`, it will speed up development.
- Add `Server` side code to app under separate module.
> Tpbot/ Add SocketIO for Human Connection

- piano-hero/mobile/build.gradle
- piano-hero/mobile/src/main/AndroidManifest.xml
- piano-hero/mobile/src/main/java/com/novoda/pianohero/AndroidThingsActivity.java
Lets get ready to rumble, i have set us up the bomb
> Piano Hero - AndroidThings

- piano-hero/mobile/src/main/java/com/novoda/pianohero/GameMvp.java
- piano-hero/mobile/src/main/java/com/novoda/pianohero/GameOverViewModel.java
- piano-hero/mobile/src/main/java/com/novoda/pianohero/GamePresenter.java
- piano-hero/mobile/src/main/java/com/novoda/pianohero/SimpleNotesOutputView.java
Use a view model for game over for consistency as well
note, this one is created in the presenter, maybe it should come from the model. Not a problem until we make our converter
> use view model for consistency

- piano-hero/core/src/main/java/com/novoda/pianohero/GameMvp.java
- piano-hero/mobile/src/main/java/com/novoda/pianohero/AndroidThingsActivity.java
- piano-hero/mobile/src/main/java/com/novoda/pianohero/GameModel.java
- piano-hero/mobile/src/main/java/com/novoda/pianohero/GamePresenter.java
- piano-hero/mobile/src/test/java/com/novoda/pianohero/GameModelTest.java
- stops the activity doing anything but init
bear with me @ataulm , if we have it like this, I can now add the Buzzer noises to the View to make a noise when a key is pressed. I've split it into two parts, so maybe this is wrong but I just want to see what it would be like, totally rambling now, look at the code!
> Move the input sensor into the model

- espresso-support/build.gradle
Just upping the version number prior to release
> Update espresso-support version number for release 0.2.1

- AlexaSpaceQuiz/lambda/custom/index.js
Convert the `:ask` and `:tell` emissions to `:askWithCard` and `:tellWithCard` so that the Echo Show can display the text
> [Alexa Space] Improve Echo Show display

- AlexaSpaceQuiz/lambda/custom/index.js
- AlexaSpaceQuiz/models/en-US.json
Add a new Intent to handle the start of the quiz
Before | After | After + Unknown intent
--- | --- | ---
> [Alexa Space] Fix start intent

- AlexaSpaceQuiz/lambda/custom/index.js
- AlexaSpaceQuiz/lambda/custom/question.js
... if present, otherwise just show the traditional answer
> [Alexa Space] follow up sentence

- AlexaSpaceQuiz/lambda/custom/index.js
- AlexaSpaceQuiz/lambda/custom/package-lock.json
- AlexaSpaceQuiz/lambda/custom/package.json
- AlexaSpaceQuiz/skill.json
Display questions using cards with background with a random space image on each one.
The images are from Pixbay and are all Free for commercial use without any need for attribution.
(the questions are still the ones related to reindeers, the final content will be added in a later PR)
> [Alexa Space] Create cards with background

- AlexaSpaceQuiz/lambda/custom/question.js
No more reindeers!
We have 26 questions so far
> [Alexa Space] Space questions

- AlexaSpaceQuiz/.ask/config
- AlexaSpaceQuiz/models/en-US.json
- AlexaSpaceQuiz/skill.json
Update the skill id to use the Novoda account
> [Alexa Space] final skill id

- AlexaSpaceQuiz/lambda/custom/index.js
Fixes the Help intent text so that it makes sense with what it actually does (it said 'do you want to start a new game?' but it actually continued the in-progress game, so changed the text to say 'do you want to continue playing?')
Before | After 
--- | ---
And also I've added a new `STOP` state to allow easier handling of the intents when the user wants to stop the game (this made it easy to fix the bug where instead of starting a new game it'd resume the in-progress one).
Before | After 
--- | ---
(notice the question at the bottom, it used to repeat the question whereas now it actually starts a new game)
> [Alexa Space] Fix Stop and Help intents

- AlexaSpaceQuiz/skill.json
Update summary, example phrases, description and testing instructions.
Also, added keywords for better discoverability of the skill
> [Alexa Space] update publishing info

- AlexaSpaceQuiz/skill.json
Use sample phrases from model for certification
> [Alexa Space] sample phrases

- AlexaSpaceQuiz/skill.json
Copying the en-US one, it is required for certification
> [Space Quiz] Add en-GB store listing

- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/BoardModel.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/BoardModelImpl.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/BoardPresenter.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/BoardView.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/patterns/PatternRepository.kt
- game-of-life-multiplatform/game-of-life-js/src/main/kotlin/com/novoda/gol/components/App.kt
- game-of-life-multiplatform/game-of-life-js/src/main/kotlin/com/novoda/gol/components/Board.kt
**Description**
We extracted a simple MVP out of the react client which then can be later reused on other platforms, e.g. android.
paired with @tasomaniac
> [GoL] Extract MVP which can be shared among platforms

- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/GameLoop.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/PositionEntity.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/data/BoardEntity.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/data/CellEntity.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/data/CellMatrix.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/data/GameLoop.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/data/ListBasedMatrix.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/data/PositionEntity.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/data/SimulationBoardEntity.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/patterns/AbstractPattern.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/patterns/Blinker.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/patterns/Glider.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/patterns/PatternEntity.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/presentation/BoardModel.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/presentation/BoardModelImpl.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/presentation/BoardPresenter.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/presentation/BoardView.kt
- game-of-life-multiplatform/game-of-life-js/src/main/kotlin/com/novoda/gol/GameLoop.kt
- game-of-life-multiplatform/game-of-life-js/src/main/kotlin/com/novoda/gol/components/App.kt
- game-of-life-multiplatform/game-of-life-js/src/main/kotlin/com/novoda/gol/components/Board.kt
- game-of-life-multiplatform/game-of-life-js/src/main/kotlin/com/novoda/gol/components/cell.kt
- game-of-life-multiplatform/game-of-life-js/src/main/kotlin/com/novoda/gol/data/GameLoop.kt
- game-of-life-multiplatform/game-of-life-jvm/src/main/kotlin/com/novoda/gol/terminal/Main.kt
- game-of-life-multiplatform/game-of-life-jvm/src/test/kotlin/BoardEntityTest.kt
**Description**
We extracted a `GameLoop` which is an `expected` class with an `actual` implementation for each platform and use it in our `BoardModelImpl`.
Paired with @tasomaniac
> [GoL] Extract game loop

- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/data/SimulationBoardEntity.kt
- game-of-life-multiplatform/game-of-life-jvm/build.gradle
- game-of-life-multiplatform/game-of-life-jvm/src/main/kotlin/com/novoda/gol/GameLoop.kt
- game-of-life-multiplatform/game-of-life-jvm/src/main/kotlin/com/novoda/gol/presentation/AppTerminalView.kt
- game-of-life-multiplatform/game-of-life-jvm/src/main/kotlin/com/novoda/gol/presentation/BoardTerminalView.kt
- game-of-life-multiplatform/game-of-life-jvm/src/main/kotlin/com/novoda/gol/terminal/Main.kt
**Description**
This adds platform specific view for the terminal client and reuses the previously extracted facilities  like models and presenters.
Also it fixes a bug that changes the board size when applying a pattern.
Paired with @tasomaniac
> [Gol] Update Terminal Client

- game-of-life-multiplatform/android/src/main/java/com/novoda/gol/GameOfLife.kt
- game-of-life-multiplatform/android/src/main/java/com/novoda/gol/presentation/AndroidAppView.kt
- game-of-life-multiplatform/android/src/main/res/layout/activity_game_of_life.xml
- game-of-life-multiplatform/android/src/main/res/layout/app_view.xml
**Description**
Extract `AndroidAppView` out of the `GameOfLife` Activity to separate concerns.
> [GoL] Extract app android view

- game-of-life-multiplatform/README.md
- game-of-life-multiplatform/desktop-jvm/build.gradle
- game-of-life-multiplatform/desktop-jvm/src/main/kotlin/com/novoda/gol/GameOfLife.kt
- game-of-life-multiplatform/desktop-jvm/src/main/kotlin/com/novoda/gol/presentation/DesktopAppView.kt
- game-of-life-multiplatform/desktop-jvm/src/main/kotlin/com/novoda/gol/presentation/DesktopBoardView.kt
- game-of-life-multiplatform/settings.gradle
A quickly hacked demo of a desktop-jvm module written in kotlin and based on TornadoFX
> Add desktop-jvm module written with tornado fx

- game-of-life-multiplatform/build.gradle
- game-of-life-multiplatform/gradle.properties
Kotlin/Native 0.6 has been officially [released](https://blog.jetbrains.com/kotlin/2018/02/kotlinnative-v0-6-is-here/). This PR upgrades our multiplatform project to the latest version.
> [GOL] Upgrade to latest kotlin native release

- sliceanddice/LICENSE
- sliceanddice/README.md
This PR adds a `LICENSE` and a `README` to the `sliceanddice` folder
> Slice&dice docs

- LICENSE
- README.md
* Improve root readme
* Add root LICENSE file
> Improve root repo docs

- links/.firebaserc
- links/.gitignore
- links/.vscode/settings.json
- links/database.rules.json
- links/firebase.json
- links/functions/index.js
- links/functions/package-lock.json
- links/functions/package.json
- links/package-lock.json
- links/package.json
- links/site/.babelrc
- links/site/package-lock.json
- links/site/package.json
- links/site/src/config.example.js
- links/site/src/index.html
- links/site/src/index.js
- links/site/webpack.config.js
- A firebase function which reads the request path to match a key against a url in a firebase realtime database to redirect to.
- A react website to admin (add/remove) links
> Url proxy site for maintaining consistent friendly urls

- hello-electron/README.md
- hello-electron/package-lock.json
- hello-electron/package.json
- hello-electron/test/spec.js
- Add Spectron, Mocha, Chai and Chai As Promised dependencies
- Add npm test task
- Add some basic tests for demonstration purposes
- Update README
> Hello Electron demo tests

- HelloTorchIOS/HelloTorchIOS/Base.lproj/Main.storyboard
- HelloTorchIOS/HelloTorchIOS/LightsLogic.swift
- HelloTorchIOS/HelloTorchIOS/StrobeLights.swift
- HelloTorchIOS/HelloTorchIOS/SwitchCounter.swift
- HelloTorchIOS/HelloTorchIOS/ViewController.swift
Sample app to make the device torch flash rapidly
Code is from this Stackoverflow question with some minor changes https://stackoverflow.com/questions/48956549/how-to-build-an-accurate-iphone-strobe-light-using-swift/48957759#48957759
In my tests it last for more than one hour without overheating
> hello torch iOS

- multiplatform-movies/.gitignore
- multiplatform-movies/README.md
- multiplatform-movies/build.gradle
- multiplatform-movies/common/build.gradle
- multiplatform-movies/common/src/jsMain/kotlin/com/novoda/movies/core/ApplicationDispatcher.kt
- multiplatform-movies/js/README.md
- multiplatform-movies/js/build.gradle
- multiplatform-movies/js/src/main/kotlin/com/novoda/movies/gallery/ReactApp.kt
- multiplatform-movies/js/src/main/kotlin/com/novoda/movies/gallery/main.kt
- multiplatform-movies/js/src/main/web/index.html
- multiplatform-movies/local.properties
- multiplatform-movies/settings.gradle
* Basic setup for the react project and display the number of movies
* Added gradle setup for the js module (far from being straightforward, mostly trial and errors due to the kotlin frontend plugin not grabbing the common module dependencies, maybe there's a better way?)
* Added a basic README.md to the js module
* Use presenter in the react component
* Render error or number of movies in an `h2`
* Added and fixed ignored files
* manual testing
* 🎻
> [Multiplatform Movies] - js initial setup

- microservices-swift/Sources/Application/Application.swift
- microservices-swift/Sources/Application/Routes/BoardgamesRoutes.swift
- microservices-swift/Sources/Application/Routes/HealthRoutes.swift
Refactored the CRUD solution with the following improvements: 
- Health/Boardgames router have now their own classes instead of being global scoped functions
- Initialise has been simplified in order to use only the router
> [🖥, 🧼] Refactor: Scope routes 
