novoda/spikes

- compare-reports/core/build.gradle
- compare-reports/core/src/main/resources/META-INF/gradle-plugins/com.novoda.compare-reports.properties
This PR adds namespaced plugin id com.novoda.compare-reports.
The old plugin id is deprecated.
This PR also updates the bintray-release plugin to use the namespaced id.
> Compare reports/Add namespaced plugin id

- ActivityTalkbackInvestigation/app/src/main/java/com/novoda/activitytalkbackinvestigation/DrawerActivity.java
- ActivityTalkbackInvestigation/app/src/main/java/com/novoda/activitytalkbackinvestigation/ProHaxDrawerActivity.java
@Electryc @blundell @Dorvaryn 
- We don't navigate on navigation item click for some reason (jankiness)
- We use the `onDrawerClosed` event to then actually navigate.
- Closing the open drawer will trigger an a11y event - it'll announce the drawer has been closed, and then it'll read the now visible (the old one) activity, followed by the new one.
I think this is because the messages are queued - Kelly Shuster mentioned something in her berlin talk about "polite" mode (I forget the details) where you can either mark your accessibility announcements as polite/brutal to wait til it's finished what it's saying or interrupt it. Perhaps it ought to be in brutal mode, but I don't think that's under our control.
> Talkback navdrawer

- enews-node/.gitignore
- enews-node/app.js
- enews-node/newsFetcher.js
- enews-node/package.json
Uses nodejs to parse all the slack general channel history for `#enews`, we can pass the amount of days to backtrace and the latest day.
run with `token=bamtoken node app.js`
```
#eNews go incognito and <http://www.twitter.com|www.twitter.com> <http://www.bbc.co.uk/news/technology-35481975>
forgot this in #enews but it seems pretty cool to me <https://sketchfab.com/>
#enews <http://motherboard.vice.com/read/google-will-soon-shame-all-websites-that-are-unencrypted-chrome-https>
#enews Combinations for a go board of 19x19 =&gt; <http://tromp.github.io/go/legal.html>
#enews: <https://twitter.com/tomgara/status/692111800289095682?s=09>
#enews <https://github.com/brave/browser-android>
#enews <http://www.bbc.co.uk/news/entertainment-arts-35371204>
#enews …
```
> Enews node variant

- ReactNative/ReactTwitter/.babelrc
- ReactNative/ReactTwitter/__tests__/core/service/deep-linking-facade.ios-test.js
- ReactNative/ReactTwitter/android/app/src/main/AndroidManifest.xml
- ReactNative/ReactTwitter/android/app/src/main/java/com/reacttwitter/MainActivity.java
- ReactNative/ReactTwitter/android/app/src/main/java/com/reacttwitter/OauthIntentModule.java
- ReactNative/ReactTwitter/android/app/src/main/java/com/reacttwitter/OauthIntentPackage.java
- ReactNative/ReactTwitter/core/service/deep-linking-facade.android.js
- ReactNative/ReactTwitter/core/service/deep-linking-facade.ios.js
- ReactNative/ReactTwitter/core/views/debug-screen.js
- ReactNative/ReactTwitter/core/views/deep-linking.js
- ReactNative/ReactTwitter/core/views/helloworld.js
- ReactNative/ReactTwitter/core/views/main-navigator.js
- ReactNative/ReactTwitter/index.android.js
- ReactNative/ReactTwitter/index.ios.js
- ReactNative/ReactTwitter/ios/ReactTwitter.xcodeproj/project.pbxproj
- ReactNative/ReactTwitter/ios/ReactTwitter/AppDelegate.m
- ReactNative/ReactTwitter/ios/ReactTwitter/Info.plist
- ReactNative/ReactTwitter/package.json
- ReactNative/ReactTwitter/react-env.js
This PR implements: 
- deep-linking functionality required as part of the oauth story.
- Debug Screen, for the moment it contains only the deep-link view
- Basic navigator (swipe from the edge of the screen to go back)
Please have a deep look at this PR as we are implementing new stuff for the first time and probably there are much better ways to accomplish the same. 
Screenshots: 
BEFORE: 
| iOS | Android |
| --- | --- |
| ![807064fc-1605-11e6-8cd5-cc8d3c8e97c4](https://cloud.githubusercontent.com/assets/797790/15188001/e21d6692-17a3-11e6-9bfe-9518890b6fd7.png) | ![889b64b0-1605-11e6-806d-78013a28e50c](https://cloud.githubusercontent.com/assets/797790/15188003/e59e8616-17a3-11e6-97a6-b515212cf375.png) |
AFTER: 
| iOS | Android |
| --- | --- |
| …
> React/PT-68/Deep Linking

- Firebase/android/app/src/main/java/com/novoda/bonfire/chat/view/ChatView.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/chat/displayer/ChatDisplayer.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/chat/presenter/ChatPresenter.java
The submit button is disabled when there is no text in the message input in order to prevent users from sending empty messages.
Paired with
@tobiasheine
> Disable submit button when message is empty

- ReactNative/ReactTwitter/__tests__/core/service/oauth-helper.test.js
- ReactNative/ReactTwitter/__tests__/core/service/percent-encoder.test.js
- ReactNative/ReactTwitter/core/service/config.json
- ReactNative/ReactTwitter/core/service/network-calls-manager.js
- ReactNative/ReactTwitter/core/service/oauth-helper.js
- ReactNative/ReactTwitter/core/service/percent-encoder.js
- ReactNative/ReactTwitter/core/service/twitter-requests-service.js
- ReactNative/ReactTwitter/core/views/debug-screen.js
- ReactNative/ReactTwitter/core/views/main-navigator.js
- ReactNative/ReactTwitter/core/views/oauth-screen.js
- ReactNative/ReactTwitter/package.json
We created two helper classes for the Twitter login flow. One that is a generic oauth helper, that creates a signature for a request and builds an authorization header. The second one is is for creating signed request to the Twitter API. For now we only have implemented the `requestToken` method that will provide a token for us to be used with login in the future.
We wrote tests for the `PercentEncoder` and `OauthHelper`, but we had to comment out the later ones because they were failing due to some react native stuff (CryptoJS to be more specific).
To test this functionality, we have included a debug screen accessible from the main screen (Oauth)
| iOS | Android |
| --- | --- |
| ![may-12-2016 17-36-15](https://cloud.githubusercontent.com/assets/2426348/15220518/10e51cf8-1868-11e6-94bd-34 …
> Access token Request

- Firebase/android/app/src/main/java/com/novoda/bonfire/Dependencies.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/channel/ChannelsActivity.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/channel/service/FirebaseChannelService.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/chat/ChatActivity.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/chat/service/FirebaseChatService.java
- Firebase/android/app/src/main/java/com/novoda/bonfire/login/service/FirebaseLoginService.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/channel/presenter/ChannelsPresenter.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/channel/service/ChannelService.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/chat/presenter/ChatPresenter.java
- Firebase/android/core/src/main/java/com/novoda/bonfire/login/service/LoginService.java
- Firebase/server/database.rules.json
Public and private channels are now displayed in the channel list. The channels are indexed separately in firebase and database rules were updated to ensure the correct access rights.
Nothing changes in the UI, the user does not know if the channel is private or public yet.
Paired with
@Dorvaryn and @dominicfreeston on the DB rules
> Firebase / Show public and private channels in channel list

- ReactNative/ReactTwitter/core/service/authentication-service.js
- ReactNative/ReactTwitter/core/service/config.json
- ReactNative/ReactTwitter/core/service/oauth-helper.js
- ReactNative/ReactTwitter/core/service/twitter-requests-service.js
- ReactNative/ReactTwitter/core/views/debug/oauth-screen.js
- ReactNative/ReactTwitter/core/views/login-screen.js
- ReactNative/ReactTwitter/core/views/main-navigator.js
- ReactNative/ReactTwitter/core/views/splash-screen.js
- ReactNative/ReactTwitter/core/views/tweetView.js
- ReactNative/ReactTwitter/core/views/tweetsList.js
- ReactNative/ReactTwitter/core/views/tweetsListItem.js
TL;DR Use real data for the tweets list and tweet details
Previously, the authorization header for the aforementioned calls was hardcoded. So now we use the `OauthHelper` to compute the real auhorization header. To achieve this, we defined methods in the `TwitterRequestsService` to help us for that, and added support for query parameters in `OauthHelper`. We also inject the `TwitterRequestsService` across the different views so we don't have to instantiate each time a new service, and we encapsulated the `AuthenticationService` logic in the service. Plus misc refactors to improve quality.
No actual screenshots, as we only touched the functionality, not the UI.
Paired with @gbasile
> React/pt 70/tweets list oauth integration

- ReactNative/ReactTwitter/core/views/tweetsList.js
Basically, added a `RefreshControl` as a `refreshControl` property of the `ListView`
BEFORE: 
| iOS | Android |
| --- | --- |
| ![ios-before](https://cloud.githubusercontent.com/assets/2426348/15425048/5da69c96-1e86-11e6-91a4-956bd8edaf3d.gif) | ![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/2426348/15425254/5c90c998-1e87-11e6-9aad-edae66d2c118.gif) |
AFTER: 
| iOS | Android |
| --- | --- |
| ![ios-after](https://cloud.githubusercontent.com/assets/2426348/15425052/6312cd30-1e86-11e6-911d-cd9ef61df948.gif) | ![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/2426348/15425251/5635afdc-1e87-11e6-8f43-cd3c188b9ae9.gif) |
Paired with no one
> Add pull-to-refresh mechanism for tweets list

- Firebase/ios/Bonfire.xcodeproj/project.pbxproj
- Firebase/ios/Bonfire/Core/Channel/ChannelsPresenter.swift
- Firebase/ios/Bonfire/Core/Config.swift
- Firebase/ios/Bonfire/Mobile/AppDelegate.swift
- Firebase/ios/Bonfire/Mobile/Channel/ChannelsViewController.swift
- Firebase/ios/Bonfire/Mobile/FirebaseRemoteConfig.swift
- Firebase/ios/Podfile
- Firebase/ios/Podfile.lock
A very simple example of using Firebase Remote Config, to sort all channels by name rather than separate Public and Private channels (the default).
> Remote config

- Firebase/ios/Bonfire.xcodeproj/project.pbxproj
- Firebase/ios/Bonfire/Mobile/AppDelegate.swift
- Firebase/ios/Bonfire/Mobile/FirebaseDynamicLinkFactory.swift
- Firebase/ios/Bonfire/Mobile/FirebaseRemoteConfig.swift
... and some imports were added that were required to prevent build errors.
Basically, dynamic links are now cross platform 🎉
> Added android package name to dynamic link,

- Architecture/TodoApp/android/core/src/main/java/com/novoda/todoapp/tasks/data/source/InMemoryLocalTaskDataSource.java
- Architecture/TodoApp/android/core/src/main/java/com/novoda/todoapp/tasks/data/source/InMemoryRemoteTaskDataSource.java
- Architecture/TodoApp/android/core/src/main/java/com/novoda/todoapp/tasks/presenter/TasksPresenter.java
- Architecture/TodoApp/android/core/src/main/java/com/novoda/todoapp/tasks/service/PersistedTasksService.java
- Architecture/TodoApp/android/mobile/src/main/java/com/novoda/todoapp/tasks/view/loading/AndroidTasksLoadingDisplayer.java
When unsubscribing from the tasks the behaviour was bound to the scheduler and any init still running would be cancelled.
We now allow the init fetch to continue running and cache it's result so that when the next client subscribes the data is there.
> Avoid cancelling fetch when unsubscribing from the data

- BuildPropertiesPlugin/build.gradle
- BuildPropertiesPlugin/gradle/publish.gradle
- BuildPropertiesPlugin/plugin/src/integrationTest/groovy/com/novoda/buildproperties/SampleProjectTest.groovy
- BuildPropertiesPlugin/sample/app/build.gradle
Version `0.9.5` of the `build-properties-plugin` has been released to Bintray with the wrong coordinates:
```
<groupId>com.novoda.build-properties</groupId>
<artifactId>build-properties</artifactId>
<version>0.9.5</version>
```
We want to align our artifacts to always use `com.novoda` as groupId, removing the redundant artifactId from it. This leads to the deploy of version `0.9.6`. The new pom will look like:
```
<groupId>com.novoda</groupId>
<artifactId>build-properties-plugin</artifactId>
<version>0.9.6</version>
```
> BuildProertiesPlugin: Fix maven coordinates

- enews-node/app.js
- enews-node/newsFetcher.js
- enews-node/slack.js
Problem -
Parsing enews was failing due to a slack room being created the same name, enews was being replaced with #C0YNBKANM
There was also some extra information that is useful to attach the the messages, such as the posters name and the news link, title and image.
Solution 
- Filter messages by including the slack room id
- linking message userIds to to Users to give us the message posters real name
```
{ 
originalMessage: '<#C0YNBKANM|enews> A giant floating barrier might be the answer to cleaner     
oceans \n<http://yahoonewsdigest-us.tumblr.com/146517763724>',
title: 'A giant floating barrier might be the answer to cleaner oceans',
link: 'http://yahoonewsdigest-us.tumblr.com/146517763724',
poster: 'Wagner Truppel',
imageUrl: …
```
> #eNews node v2

- Architecture/TodoApp/android/core/src/main/java/com/novoda/todoapp/navigation/Navigator.java
- Architecture/TodoApp/android/core/src/main/java/com/novoda/todoapp/statistics/data/model/Statistics.java
- Architecture/TodoApp/android/core/src/main/java/com/novoda/todoapp/statistics/displayer/StatisticsDisplayer.java
- Architecture/TodoApp/android/core/src/main/java/com/novoda/todoapp/statistics/presenter/StatisticsPresenter.java
- Architecture/TodoApp/android/core/src/main/java/com/novoda/todoapp/statistics/service/StatisticsService.java
- Architecture/TodoApp/android/core/src/main/java/com/novoda/todoapp/statistics/service/TasksStatisticsService.java
- Architecture/TodoApp/android/core/src/main/java/com/novoda/todoapp/tasks/displayer/TasksActionListener.java
- Architecture/TodoApp/android/core/src/main/java/com/novoda/todoapp/tasks/presenter/TasksPresenter.java
- Architecture/TodoApp/android/core/src/test/kotlin/com/novoda/todoapp/statistics/presenter/StatisticsPresenterTest.kt
- Architecture/TodoApp/android/core/src/test/kotlin/com/novoda/todoapp/statistics/service/TasksStatisticsServiceTest.kt
- Architecture/TodoApp/android/mobile/src/main/AndroidManifest.xml
- Architecture/TodoApp/android/mobile/src/main/java/com/novoda/todoapp/TodoApplication.java
- Architecture/TodoApp/android/mobile/src/main/java/com/novoda/todoapp/navigation/AndroidNavigator.java
- Architecture/TodoApp/android/mobile/src/main/java/com/novoda/todoapp/statistics/StatisticsActivity.java
- Architecture/TodoApp/android/mobile/src/main/java/com/novoda/todoapp/statistics/view/StatisticsView.java
- Architecture/TodoApp/android/mobile/src/main/java/com/novoda/todoapp/tasks/view/TasksView.java
- Architecture/TodoApp/android/mobile/src/main/res/layout/merge_statistics_view.xml
- Architecture/TodoApp/android/mobile/src/main/res/layout/statistics_activity.xml
- Architecture/TodoApp/android/mobile/src/main/res/menu/tasks_menu.xml
- Architecture/TodoApp/android/mobile/src/main/res/values/strings.xml
In our quest to get all features from the Google sample into this app, here is the statistics screen.
We access it through the overflow menu at the moment. The nav drawer can be implemented as a separate PR.
| Desired | After |
| ----- | ----- |
|![device-2016-07-07-114130](https://cloud.githubusercontent.com/assets/610924/16655649/3a3aabb0-4453-11e6-8c82-45f279fd8771.png)|![device-2016-07-07-150146](https://cloud.githubusercontent.com/assets/610924/16655746/c45cb950-4453-11e6-85c9-2086a108b78b.png)|
|![device-2016-07-07-114632](https://cloud.githubusercontent.com/assets/610924/16655657/4ca9cd1c-4453-11e6-8300-8671e6f39156.png)|![device-2016-07-07-150120](https://cloud.githubusercontent.com/assets/610924/16655763/d4a0b0c8-4453-11e6-8954-bc63e21c7ef3.png)|
> Introducing a very lightweight Statistics screen.

- BuildPropertiesPlugin/plugin/src/main/groovy/com/novoda/buildproperties/FilePropertiesEntries.groovy
- BuildPropertiesPlugin/plugin/src/test/groovy/com/novoda/buildproperties/FilePropertiesEntriesTest.groovy
- BuildPropertiesPlugin/plugin/src/test/resources/including.properties
- BuildPropertiesPlugin/plugin/src/test/resources/more.properties
We found useful to have properties files that can recursively include other properties files specified in a `include` property. This can help composing set of properties in a hierarchical way allowing to define cohesive sets of properties and helping reusing them. Inherited properties can be overridden by the including set, just redefine the property in the file and its value will be used instead of the one from the included set.
> BuildPropertiesPlugin: Introduce recursive include support for properties

- BuildPropertiesPlugin/CHANGELOG.md
- BuildPropertiesPlugin/README.md
- BuildPropertiesPlugin/build.gradle
- BuildPropertiesPlugin/plugin/src/main/groovy/com/novoda/buildproperties/BuildProperties.groovy
- BuildPropertiesPlugin/plugin/src/test/groovy/com/novoda/buildproperties/BuildScriptTest.groovy
- Added possibility to provide custom error message when specified properties file not found.
- Fixed README to remove mention of lazy-loading of files because inaccurate.
> BuildPropertiesPlugin: Prepare v1.0.1

- BuildPropertiesPlugin/README.md
- BuildPropertiesPlugin/plugin/build.gradle
- BuildPropertiesPlugin/plugin/src/main/groovy/com/novoda/buildproperties/CompositeException.groovy
- BuildPropertiesPlugin/plugin/src/main/groovy/com/novoda/buildproperties/Entry.groovy
- BuildPropertiesPlugin/plugin/src/test/groovy/com/novoda/buildproperties/CompositeExceptionSubject.groovy
- BuildPropertiesPlugin/plugin/src/test/groovy/com/novoda/buildproperties/CompositeExceptionTest.groovy
- BuildPropertiesPlugin/plugin/src/test/groovy/com/novoda/buildproperties/EntrySubject.groovy
- BuildPropertiesPlugin/plugin/src/test/groovy/com/novoda/buildproperties/EntryTest.groovy
- BuildPropertiesPlugin/plugin/src/test/groovy/com/novoda/buildproperties/SampleProjectTest.groovy
- BuildPropertiesPlugin/sample/app/build.gradle
Every subclass of `Entries` (eg: `FilePropertiesEntries`) defines if the evaluation of an `Entry` will throw when a property is missing. In such cases we may want to avoid to break the build and to define a fallback via the `or()` operator instead. A fallback can be:
- another `Entry`, eg: `entry.or(buildProperties.secrets['fallback'])`
- a `Closure`, eg: `entry.or({ Math.random() })`
- a simple value, eg: `entry.or('fallback')`
(where `entry` is an instance of `Entry`, eg: `buildProperties.secrets['foo']`)
If the whole fallback chain fails then a `CompositeException` is thrown listing all
the causes of failure encountered evaluating the chain, eg:
```
A problem occurred while evaluating entry:
- No value defined for property 'foo' in 'secrets' properties
- No value defined for property …
```
> BuildPropertiesPlugin: Introduce fallback support

- BuildPropertiesPlugin/README.md
- BuildPropertiesPlugin/build.gradle
- BuildPropertiesPlugin/plugin/build.gradle
- BuildPropertiesPlugin/plugin/src/main/groovy/com/novoda/buildproperties/BuildPropertiesPlugin.groovy
- BuildPropertiesPlugin/plugin/src/main/groovy/com/novoda/buildproperties/EnvironmentPropertiesEntries.groovy
- BuildPropertiesPlugin/plugin/src/test/groovy/com/novoda/buildproperties/EnvironmentPropertiesEntriesTest.groovy
- BuildPropertiesPlugin/plugin/src/test/groovy/com/novoda/buildproperties/SampleProjectTest.groovy
- BuildPropertiesPlugin/sample/app/build.gradle
A built-in set of entries `env` can be used to access an environment variable as `Entry`, like this:
```groovy
Entry entry = buildProperties.env['SOME_ENVIRONMENT_VAR']
```
If the key specified is not defined as environment variable an `IllegalArgumentException` is thrown.
> This is the last feature for version `1.1.0` of the plugin
> BuildPropertiesPlugin: Introduce support for environment variables

- BuildPropertiesPlugin/CHANGELOG.md
- BuildPropertiesPlugin/README.md
- BuildPropertiesPlugin/build.gradle
- BuildPropertiesPlugin/plugin/src/main/groovy/com/novoda/buildproperties/BuildProperties.groovy
- BuildPropertiesPlugin/plugin/src/test/groovy/com/novoda/buildproperties/BuildScriptTest.groovy
- BuildPropertiesPlugin/sample/app/build.gradle
At the moment the project evaluation fails straight away when `buildProperties` contains a set of entries from a file that is not found.
It would be useful in multiple scenarios to lazy load properties file and fail the build only when one of their entries will actually be evaluated.
> BPP: Add lazy-loading of properties files

- monkey-runner/README.md
- monkey-runner/dependencies.gradle
- monkey-runner/plugin/build.gradle
- monkey-runner/plugin/src/main/groovy/com/novoda/monkey/MonkeyConfigurationPlugin.groovy
- monkey-runner/plugin/src/main/groovy/com/novoda/monkey/MonkeyRunnerExtension.groovy
- monkey-runner/plugin/src/test/groovy/com/novoda/monkey/MonkeyConfigurationPluginTest.groovy
- monkey-runner/plugin/src/test/groovy/com/novoda/monkey/MonkeyRunnerExtensionTest.groovy
- monkey-runner/sample/app/src/main/AndroidManifest.xml
Make `categories` optional. 
Introduce `useMonkeyTrap` property in order to control whether the session should use the trap or not. 
The plugin requires an explicit `android.intent.category.MONKEY` intent filter category which adds noise to the application under test, this could be optional. 
Moreover, the plugin automatically starts the monkey trap for every session. In certain cases the monkey trap is not required, thus making the monkey trap optional would be beneficial. 
- removed the explicit `android.intent.category.MONKEY` intent filter category and added an optional `categories` property to the extension for configuration
- added an optional `useMonkeyTrap`property on the extension in order to control whether the trap should be launched or not. However, the default value of this …
> Monkey runner plugin/Optional properties

- BuildPropertiesPlugin/CHANGELOG.md
- BuildPropertiesPlugin/README.md
- BuildPropertiesPlugin/build.gradle
- BuildPropertiesPlugin/plugin/src/main/groovy/com/novoda/buildproperties/BuildPropertiesPlugin.groovy
- BuildPropertiesPlugin/plugin/src/test/groovy/com/novoda/buildproperties/SampleProjectTest.groovy
- BuildPropertiesPlugin/sample/app/build.gradle
APKs are not signed and zip-aligned at all if the signing configuration is read from a properties file via `signingConfigProperties`. It seems the lazy evaluation facilities introduced in the previous releases broke somehow this feature. To avoid this problem in the future a new test has been added checking the zip-aligned release APK is generated as intended.
This PR incidentally bumps the plugin version to 1.2.1 to make a new release possible.
> BuildPropertiesPlugin: Fix signing config support

- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/CheckstyleConfigurator.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/EvaluateViolationsTask.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/StaticAnalysisPlugin.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/Violations.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/CheckstyleConfigurationTest.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/Fixtures.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/LogsSubject.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/TestProject.groovy
When the build fails after running all the verification tasks we want to provide the user a meaningful log with information about what threshold has been exceeded.
- Introduced `Violations` to collect a summary of the violations encountered when running the checks. A `NamedDomainObjectContainer` will hold an instance of `Violations` for each static analysis tool applied to the project.
- Forced usage of checkstyle v7.1.2
- Made `EvaluateViolationsTask` to check all the `Violations` and provide meaningful logs detailing failures and thresholds exceeded, eg:
```
:compileJava
:processResources UP-TO-DATE
:classes
:checkstyleMain
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:checkstyleTest
:evaluateViolations FAILED
FAILURE: Build failed with an exception.
* What went wrong: …
```
> StaticAnalysisPlugin: Improve collection/evaluation of violations

- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/CheckstyleConfigurator.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/PenaltyExtension.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/QuietLogger.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/StaticAnalysisPlugin.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/CheckstyleConfigurationTest.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/CheckstyleIntegrationTest.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/PenaltyExtensionTest.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/LogsSubject.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/PenaltyExtensionSubject.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/TestAndroidProject.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/TestProject.groovy
This PR focuses on improving the Checkstyle support in the `static-analysis-plugin`:
- It's now possible to specify a configuration file detailing the Checkstyle modules for the static analysis. To achieve so it's just needed to use the [`config`](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.Checkstyle.html#org.gradle.api.plugins.quality.Checkstyle:config)/[`configFile`](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.Checkstyle.html#org.gradle.api.plugins.quality.Checkstyle:configFile) property in the checkstyle extension, eg:
```gradle
staticAnalysis {
checkstyle {
configFile project.file('foo.xml')
}
}
```
- To allow to easily exclude files from the analysis the original checkstyle extension has been extended with a `exclude` method that accepts …
> static-analysis-plugin/Checkstyle configuration improvements

- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/TestAndroidProject.groovy
The Android project tests are failing because `local.properties` can't be found. 
To fix the problem, try to include the file only if it exists.
Paired with @mr-archano
> static-analysis-plugin/Fix for "FileNotFoundException"

- static-analysis-plugin/README.md
- static-analysis-plugin/plugin/build.gradle
- static-analysis-plugin/plugin/fixtures/pmd/config/rules.xml
- static-analysis-plugin/plugin/fixtures/pmd/priority1/Priority1Violator.java
- static-analysis-plugin/plugin/fixtures/pmd/priority2/Priority2Violator.java
- static-analysis-plugin/plugin/fixtures/pmd/priority3/Priority3Violator.java
- static-analysis-plugin/plugin/fixtures/pmd/priority4/Priority4Violator.java
- static-analysis-plugin/plugin/fixtures/pmd/priority5/Priority5Violator.java
- static-analysis-plugin/plugin/fixtures/pmd/reports/sample.xml
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/CheckstyleConfigurator.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/PmdConfigurator.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/PmdViolationsEvaluator.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/StaticAnalysisPlugin.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/CheckstyleIntegrationTest.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/PmdIntegrationTest.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/PmdViolationsEvaluatorTest.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/Fixtures.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/LogsSubject.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/TestProject.groovy
> Tracked in JIRA by [PT-276](https://novoda.atlassian.net/browse/PT-276)
We want to use the `static-analysis-plugin` to easily integrate PMD in a Java or Android project. Features should be in parity with the current Checkstyle integration:
- evaluation of violations grouped as warnings or errors
- introduce exclude filters to ignore paths from the PMD analysis
- logging facilities detailing limits exceeded and relevant reports
- disable PMD integration if no configuration provided
- Added fixtures for both rules and java files to be used in integration tests.
- Introduced `PmdViolationsEvaluator` as delegate used to evaluate violations listed in the PMD reports.
- Introduced `PmdConfigurator` to delegate configuration of PMD for Java/Android projects
- Amended `TestProject` builder to …
> PT-272/PT-276: Integrate PMD

- drop-cap/README.md
- drop-cap/library/src/main/java/com/novoda/dropcap/DropCapView.java
- drop-cap/library/src/main/res/values/attrs.xml
- drop-cap/sample/src/main/java/com/novoda/dropcap/demo/DropCapActivity.java
- drop-cap/sample/src/main/res/layout/activity_drop_cap.xml
When editing the size of the DropCap and changing the length of the text input it is possible that the DropCap will overlap the copy text (below).
| | | |
|:----:|----|----|
| **Before** |![drop_cap](https://cloud.githubusercontent.com/assets/3380092/19923174/1f8b13bc-a0de-11e6-908b-e2a0d994bc48.jpg)| |
| **After** | ![drop_cap](https://cloud.githubusercontent.com/assets/3380092/20004464/638380e8-a284-11e6-8c35-6c473069cd4d.png) | ![not_enough_text](https://cloud.githubusercontent.com/assets/3380092/20004465/6385c7d6-a284-11e6-875e-b1647968865b.png) |
The second problem occurs when editing the text to display. I wrongly assumed that a call to `requestLayout` would perform a `measure` and `draw` call...which it does...but...apparently a `requestLayout` is always paired with a call to …
> Drop cap fixes

- static-analysis-plugin/README.md
- static-analysis-plugin/plugin/build.gradle
- static-analysis-plugin/plugin/fixtures/findbugs/high/HighPriorityViolator.java
- static-analysis-plugin/plugin/fixtures/findbugs/low/LowPriorityViolator.java
- static-analysis-plugin/plugin/fixtures/findbugs/medium/MediumPriorityViolator.java
- static-analysis-plugin/plugin/fixtures/findbugs/reports/sample.xml
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/QuietLogger.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/StaticAnalysisPlugin.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/findbugs/FinbugsViolationsEvaluator.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/findbugs/FindbugsConfigurator.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/findbugs/QuietFindbugsPlugin.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/FindbugsIntegrationTest.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/PmdIntegrationTest.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/findbugs/FindbugsViolationsEvaluatorTest.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/Fixtures.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/LogsSubject.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/TestProject.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/TestProjectSubject.groovy
> Tracked in JIRA by [PT-277](https://novoda.atlassian.net/browse/PT-277)
We want to use the `static-analysis-plugin` to easily integrate FindBugs in a Java or Android project. Features should be in parity with the current Checkstyle and PMD integration:
- evaluation of violations grouped as warnings or errors
- introduce exclude filters to ignore paths from the FindBugs analysis
- logging facilities detailing limits exceeded and relevant reports
- disable FindBugs integration if no configuration provided
- Added fixtures for both rules and java files to be used in integration tests.
- Introduced `FindBugsViolationsEvaluator` as delegate used to evaluate violations listed in the FindBugs xml reports. Apparently FindBugs supports three level of warnings (from higher to lower: `priority_1`, …
> PT-272/PT-277: Integrate Findbugs in static-analysis-plugin

- slacker/server/widget/coverage.js
#185 introduced a `config.json` file where we can dump tokens instead of exporting the variables.
There was a slight error where we where getting back from the `config.json` file an `apiKey` instead of `token` for the sonar part.
Fixed it ✨
> Slacker: Fix using token instead of apiKey for sonar

- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/LogsSubject.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/PenaltyExtensionSubject.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/test/TestProjectSubject.groovy
> Tracked in JIRA by [PT-298](https://novoda.atlassian.net/browse/PT-298)
We are using [`Truth`](https://github.com/google/truth) as assertion framework in our tests. This allows us to offering extensions to the assertions API tailored to the targets of our tests. We noticed in few places the implementation was incorrectly forcing assertions defeating the whole ["_We've made failure a strategy_"](https://github.com/google/truth#truth) mantra.
- Amended the custom `Subject`s to retrieve the current testing verb (ie: `assert` vs `assume`) instead of enforcing one in the implementation. This is possible via [`Subject#check()`](http://google.github.io/truth/api/latest/com/google/common/truth/Subject.html#check()), that allows to chain other `Subject` within our custom propositional logic
- …
> PR-272/PT-298: Use testing verb correctly in custom subjects for static-analysis-plugin

- static-analysis-plugin/build.gradle
- static-analysis-plugin/gradle/publish.gradle
- static-analysis-plugin/plugin/build.gradle
> Tracked in JIRA by [PT-294](https://novoda.atlassian.net/browse/PT-294)
We want to integrate the plugin in some of the running projects in Novoda. For this we need to publish an artifact to Bintray.
The publishing configuration will use the [`bintray-release`](https://github.com/novoda/bintray-release/) plugin. The current version of the plugin is set to `0.1`. The artifact will be deployed via our Jenkins as usual.
Manually checked the artifact is created correctly along with the `pom.xml` when the `bintrayUpload` task is executed.
> Paired with @eduardb
> PT-294: Integrate bintray-release plugin to publish static-analysis-plugin artifact

- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/EvaluateViolationsTask.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/StaticAnalysisPlugin.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/internal/QuietLogger.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/internal/Violations.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/internal/checkstyle/CheckstyleConfigurator.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/internal/findbugs/FinbugsViolationsEvaluator.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/internal/findbugs/FindbugsConfigurator.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/internal/findbugs/QuietFindbugsPlugin.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/internal/pmd/PmdConfigurator.groovy
- static-analysis-plugin/plugin/src/main/groovy/com/novoda/staticanalysis/internal/pmd/PmdViolationsEvaluator.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/internal/checkstyle/CheckstyleIntegrationTest.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/internal/findbugs/FindbugsIntegrationTest.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/internal/findbugs/FindbugsViolationsEvaluatorTest.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/internal/pmd/PmdIntegrationTest.groovy
- static-analysis-plugin/plugin/src/test/groovy/com/novoda/staticanalysis/internal/pmd/PmdViolationsEvaluatorTest.groovy
> Tracked in JIRA by [PT-299](https://novoda.atlassian.net/browse/PT-299)
Almost all of the classes (except for some related to Findbugs - @mr-archano was a visionary) were in the main package, making it a bit hard to identify the different tools that this plugin uses.
- Create a subpackage for each of the tools (PMD, Findbugs and Checkstyle) under an `internal` subpackage, and move the classes to the adequate package
| Before | After |
| ----- | ----- |
| ![screenshot 2016-11-09 11 12 14](https://cloud.githubusercontent.com/assets/2426348/20135017/f68f058c-a66d-11e6-9f7c-4cc6a0430229.png) | ![screenshot 2016-11-09 11 11 07](https://cloud.githubusercontent.com/assets/2426348/20135022/fb529c0a-a66d-11e6-8877-8c5a2db43726.png) |
Refactoring only. Tests are still passing.
> Paired with …
> Move classes to subpackages

- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/support/TextViewWithForeground.java
- TelepresenceBot/mobile/src/main/res/drawable-v21/landing_option_foreground.xml
- TelepresenceBot/mobile/src/main/res/drawable/landing_option_foreground.xml
- TelepresenceBot/mobile/src/main/res/layout/activity_landing.xml
- TelepresenceBot/mobile/src/main/res/values/attrs.xml
- TelepresenceBot/mobile/src/main/res/values/colors.xml
- TelepresenceBot/mobile/src/main/res/values/styles.xml
We have a landing screen but the clickable items do not have any touch states. 
Rather than wrapping the items in a view that handles foreground (FrameLayout) we'll create a `TextView` that can support a `foreground`.
> TpBot: Add a TextViewWithForeground

- TelepresenceBot/mobile/build.gradle
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/support/Observable.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/support/Observer.java
- TelepresenceBot/mobile/src/test/java/com/novoda/tpbot/support/ObservableTest.java
We want to be able to perform an asynchronous call but keep it as far away from the `Presenter` as possible. 
Implement `Observer` pattern to supply results to the `Presenter` when a new value is emitted by the `TpService`.
The `Presenter` and `Service` are coming up in the next PR so bare with me 👅 This also gave me the opportunity to implement a simple `Observer` rather than using Rx, which I haven't done before 😄
> TpBot: Observer

- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/bot/BotActivity.java
- TelepresenceBot/mobile/src/main/res/menu/bot_menu.xml
- TelepresenceBot/mobile/src/main/res/values/strings.xml
In the future, we will need to know the Product ID and Vendor ID of USB connected Arduino, so that we can whitelist it and start our app automatically when connected.
This PR adds a useful menu item that shows in a toast these detail for every connected USB device (if any).
> Tpbot/List connected USB devices

- eslint-config-novoda/.eslintrc.json
- eslint-config-novoda/README.md
- eslint-config-novoda/index.js
- eslint-config-novoda/package.json
A few Novoda projects now use NodeJS as environment. Most of the times pull requests are all about coding guidelines and standards that have to be enforced manually.
Most of our NodeJS projects now use ESLint, but the configuration is still project-local and has to be repeated across all repositories.
This PR aims at publishing a `npm` module with our agreed-upon style.
Please read the `README` for a detailed explanation of what rules are being enforced, and how.
Read [this link](http://eslint.org/docs/developer-guide/shareable-configs) to understand how to create shareable configurations like this one.
**NOTE**: as of now, the module is not published on `npm` yet. In order to test it in your projects, clone this branch and do a `npm link`. Then, in your project, run `npm link …
> Add Novoda ESLint rules for NodeJS projects

- gradle-diff-task-dependencies/plugin/build.gradle
- gradle-diff-task-dependencies/plugin/src/main/groovy/com/novoda/gradle/diffdependencytask/ConditionalDependencyEvaluator.groovy
- gradle-diff-task-dependencies/plugin/src/main/groovy/com/novoda/gradle/diffdependencytask/DiffDependencyTaskPlugin.groovy
- gradle-diff-task-dependencies/plugin/src/main/groovy/com/novoda/gradle/diffdependencytask/MemoryConditionalDependencyRepository.groovy
- gradle-diff-task-dependencies/plugin/src/test/groovy/com/novoda/gradle/diffdependencytask/ConditionalDependencyEvaluatorTest.groovy
The differential task dependencies plugin for Gradle lacks some basic testing for the evaluation logic.
This PR introduces some refactoring that make testing easier without actually building sample Gradle projects.
After this PR is merged, we will release a first version of the plugin, so it can be used in our projects.
> Test gradle-diff-task-dependencies

- MonkeyTrap/app/build.gradle
- MonkeyTrap/app/src/main/java/com/novoda/monkeytrap/OverlayService.java
- MonkeyTrap/gradle/wrapper/gradle-wrapper.properties
This PR fixes a crash where the service is re-created with a null Intent. 
This is the default behavior when the resources are scarce (e.g someone plays Pokemon Go) on a device.
Yes, I still play and whenever I open the game, I see MonkeyTrap crashes. 
Our service was long-living which is not really necessary when the overlay is not shown.
Now we add the view only when we have the show command.
We stop the Service completely when we have the hide command. This also removes the overlay automatically.
> [monkey-trap] Fix NullPointerException caused by Service recreation

- gradle-nonnull-plugin/plugin/src/main/groovy/com.novoda.gradle.nonnull/GeneratePackageAnnotationsTask.groovy
- gradle-nonnull-plugin/plugin/src/test/groovy/com/novoda/gradle/nonnull/AndroidProjectIntegrationTest.groovy
Currently, we plugin works on java and android modules. 👍 
But the task runs in every build process. This is not something we want to have.
If no package structure has changed, we don't want to run again. 
A field called `packages` created with annotation `@Input`
The code block that computes the packages is extracted into a `@Memoized` getter method: `getPackages`
- A test is added that runs the project again and asserts that we get the UP-TO-DATE check
- Another test is added that adds a new file to a new package and asserts that we didn't get UP-TO-DATE check. 
Paired with @tobiasheine
> [NNP] PT-392: up to date check support

- monkey-runner/README.md
- monkey-runner/dependencies.gradle
- monkey-runner/plugin/src/main/groovy/com/novoda/monkey/MonkeyConfigurationPlugin.groovy
- monkey-runner/plugin/src/main/groovy/com/novoda/monkey/MonkeyRunnerExtension.groovy
- monkey-runner/plugin/src/test/groovy/com/novoda/monkey/MonkeyConfigurationPluginTest.groovy
- monkey-runner/plugin/src/test/groovy/com/novoda/monkey/MonkeyRunnerExtensionTest.groovy
- monkey-runner/sample/app/build.gradle
The monkey runner plugin depends on the android command one. Currently, if you don't apply the command plugin you get a cryptic/not very helpful error message: `Error:Could not get unknown property 'command' for object of type com.android.build.gradle.AppExtension`.
By ensuring the plugin is applied first (just like what's already happening with the android plugin) we can provide a better error message.
> Ensure Command plugin is applied

- monkey-runner/README.md
- monkey-runner/build.gradle
We haven't released monkey runner since its initial version.
There's been three PRs since:
- Make categories optional & introduce `useMonkeyTrap` property in order to control whether the session should use the trap or not (https://github.com/novoda/spikes/pull/155)
- Update command plugin (https://github.com/novoda/spikes/pull/251)
- Ensure command plugin applied (https://github.com/novoda/spikes/pull/260)
This PR bumps to 1.0.0 (since it's being used in projects) and adds a changelog until we get it's own repo. (Can then migrate that info to the releases branch, and/or keep a changelog file)
> [monkey-runner] Increase version to 1.0.0 for release

- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/bot/MovementService.java
Seeing a `NullPointerException` when a command is sent to the `MovementService`. Seems to be some confusion as to when `onServiceConnected(ComponentName name, IBinder service);` is called by the `Service`, it is called before `onStartCommand(Intent intent, int flags, int startId)` where the `Toaster` etc are created, resulting in an NPE.
Move creation of `Toaster` to onCreate to prevent NPE, which occurs before any of the other callbacks.
> Tpbot/ NPE on service

- monkey-runner/README.md
- monkey-runner/plugin/src/main/groovy/com/novoda/monkey/MonkeyConfigurationPlugin.groovy
- monkey-runner/plugin/src/test/groovy/com/novoda/monkey/MonkeyConfigurationPluginTest.groovy
- monkey-runner/sample/app/build.gradle
We can avoid having the users' of this plugin having to apply the android command plugin on their own, thus making it simpler to integrate this plugin in their projects.
Tests updated.
> [monkey-runner] Apply command plugin by default

- TelepresenceBot/core/src/main/java/com/novoda/tpbot/human/HumanPresenter.java
- TelepresenceBot/core/src/main/java/com/novoda/tpbot/support/Observable.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/human/HumanActivity.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/human/SocketIOTpService.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/landing/LandingActivity.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/support/SelfDestructingMessageView.java
Receiving an NPE when navigating between the `HumanActivity` and the `LandingActivity`. We are trying to remove callbacks on a `Handler` that is null.
Add guard against attempting to clear callbacks on a null `Handler`.
Stop and Start of presenting are matched to the corresponding lifecycle methods, onStop and onStart. Guard against NPEs on Presenter when detaching service and observables.
> Tpbot/ Handler exception

- monkey-runner/README.md
As correctly pointed out by @tasomaniac in #262 we should be clear/transparent about monkey-runner's dependency on the android-command plugin.
This PR adds a notice on the repo's readme about it.
Extra: we should be moving to a specific repo soon.
> [monkey-runner] Update readme

- TelepresenceBot/core/src/main/java/com/novoda/tpbot/bot/BotPresenter.java
- TelepresenceBot/core/src/main/java/com/novoda/tpbot/bot/BotView.java
- TelepresenceBot/core/src/main/java/com/novoda/tpbot/human/HumanPresenter.java
- TelepresenceBot/core/src/test/java/com/novoda/tpbot/bot/BotPresenterTest.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/bot/BotActivity.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/human/HumanActivity.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/human/SocketIOTpService.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/support/SocketConnectionObservable.java
- TelepresenceBot/mobile/src/main/res/values/strings.xml
- TelepresenceBot/server-unit/core/loggingClient.js
- TelepresenceBot/server-unit/core/server.js
- TelepresenceBot/server-unit/test/botTest.js
A `Bot` and a `Human` client can connect to each other but currently, no communication takes place.
Forward movement events from the `Human` client to the `Bot` client.
> Tpbot forward moves

- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/bot/SocketIOTpService.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/human/SocketIOTpService.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/support/Room.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/support/SocketConnectionObservable.java
- TelepresenceBot/server-unit/core/botLocator.js
- TelepresenceBot/server-unit/core/loggingClient.js
- TelepresenceBot/server-unit/core/server.js
- TelepresenceBot/server-unit/test/botLocatorTest.js
- TelepresenceBot/server-unit/test/botTest.js
- TelepresenceBot/server-unit/test/humanTest.js
Currently, the `server` only allows a single `bot` and `human` to connect to the sole `London` room. Ideally, we should pass the room in via the request query and have that `human` / `bot` join that room.
Move the decision of rooms to the `android app` and pass which room to join via the request query.
For Bots, they immediately join whichever room is passed in through the `query`, at the moment this will be `London`.
For Humans, pull all `sockets` located in the room passed through in `query`. Take all of the rooms that each socket belongs to, should be `London` and `socket.id` rooms. If the `socket.id` room for a socket is empty then that `socket` is not connected to another client and is our available bot. Before allowing the `human` to connect we modify the `query` sent to change the …
> Tpbot/ Pass room in Query

- TelepresenceBot/server-unit/core/html/index.html
- TelepresenceBot/server-unit/core/json/rooms.json
- TelepresenceBot/server-unit/core/public/css/index.css
- TelepresenceBot/server-unit/core/public/js/connect.js
- TelepresenceBot/server-unit/core/testServer.js
- TelepresenceBot/server-unit/package.json
- TelepresenceBot/server-unit/test/test.js
The plan for the `MVP` is to open a hangout to connect to the `bot` and chat with people from another office. Well if we are opening a hangout perhaps we should also create a `webClient` so that the user does not need to have both a mobile device for moving the `bot` and another device for chatting?
Create a `webpage` from which the user can navigate the `bot`. This is just the beginning of the `webClient` creating a dummy controller that hands back to our `server` but does not pass any comments through `socketIO` yet. In a follow-up PR I will add hook up `socketIO` and fully test the `webClient` part.
> Tpbot/ Web Client

- espresso-support/core/build.gradle
- espresso-support/core/src/main/java/com/novoda/espresso/AccessibilityViewMatchers.java
- espresso-support/demo/src/androidTest/java/com/novoda/movies/MovieItemViewTalkBackTest.java
- espresso-support/dependencies.gradle
This PR adds some custom matchers for the `espresso-support` library that allow the user to assert a view has custom usage hints for click and long-click actions.
If a view is clickable, the default usage hint will be "activate" so TalkBack will read aloud, "double tap to activate". This isn't very descriptive - we should set custom usage hints.
The demo shows that we can assert the custom usage hint for both click and long click actions.
:warning: The solution is only suitable for API 21 and above since `AccessibilityAction.getLabel()` is only available on that API. Added "requires api" annotations:
I tried to follow the style for `ViewMatchers.withContentDescription()`.
> [espresso-support] Add view matchers to assert custom usage hints

- TelepresenceBot/core/src/main/java/com/novoda/tpbot/bot/BotView.java
- TelepresenceBot/mobile/build.gradle
- TelepresenceBot/mobile/src/main/AndroidManifest.xml
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/automation/TelepresenceBotAccessibilityService.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/bot/BotActivity.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/support/SocketConnectionObservable.java
- TelepresenceBot/mobile/src/main/res/xml/accessibility_service_config.xml
As a `user`, I need the bot to be able to automatically connect to a hangout room when I connect to it. The problem is `hangouts` does not have a direct `intent` to open a hangout, it always requires the joiner to confirm their intent to join a video call with the `join video call` button.
Use the `AccessibilityService` to monitor `AccessibilityEvents` coming from the `com.novoda.tpbot` and `com.google.android.talk` packages. When an event originates from `com.google.android.talk` search the `AccessibilityNodes` for the `join call button` and perform an `action.CLICK` on it to confirm a video call. 
In order to use the accessibility service on your device, you need to navigate to `settings -> accessibility` to enable the service. For now, I am hard-coding the room to join in the app as …
> TpBot/ Bot Automatically open a Hangout

- code-review-tools/README.md
- code-review-tools/ios/imports
- code-review-tools/ios/lines
- code-review-tools/ios/uikit
A few scripts I used whilst evaluating clients' iOS codebases centering around code coupling.
Three scripts are added:
- `uikit` measures the number of files which import UIKit. This can be used as a (rough) indication that code is improperly coupled to UI libraries.
- `lines` simply gives the number of lines per file. This can then be used to plot a histogram. The point of this is to quickly visualise large files and begin discussions around making them smaller. See an example histogram [here](https://docs.google.com/spreadsheets/d/1m-wIygVxOLJ2KciEokNgpOHeVgIcrM5FwXkoSB-rAyI/pubchart?oid=1766467159&format=interactive)
- `imports` records the number of import statements per file. This can also be used to plot a histogram, and indicates code which is too tightly coupled to other code. See …
> Adds basic scripts for code coupling in iOS

- drop-cap/library/src/main/java/com/novoda/dropcap/DropCapView.java
- drop-cap/library/src/main/res/values/attrs.xml
- drop-cap/sample/src/main/java/com/novoda/dropcap/demo/DropCapActivity.java
- drop-cap/sample/src/main/java/com/novoda/dropcap/demo/DropCapNumberDialogDisplayer.java
- drop-cap/sample/src/main/java/com/novoda/dropcap/demo/DropCapNumberDialogFragment.java
- drop-cap/sample/src/main/java/com/novoda/dropcap/demo/OnDropCapNumberChangeListener.java
- drop-cap/sample/src/main/res/layout/activity_drop_cap.xml
- drop-cap/sample/src/main/res/layout/fragment_drop_cap_number_dialog.xml
- drop-cap/sample/src/main/res/values/drop-cap-integers.xml
- drop-cap/sample/src/main/res/values/drop-cap-strings.xml
- drop-cap/sample/src/main/res/values/drop-cap-styles.xml
- drop-cap/sample/src/main/res/values/fragment-dialog-strings.xml
- drop-cap/sample/src/main/res/values/fragment-drop-cap-number-dialog-integers.xml
As per issue #282 a `DropCap` cannot be applied to more than a single character. The most pressing example where this would be an issue is in the following (pulled from issue), where a normally `DropCapped` character is preceded by a quotation mark.
Allow the client to specify the number of characters to `DropCap`. 
In the event that the copy wrapping the `DropCap` cannot fit on the remaining width of the `viewPort` the `DropCap` is not drawn. Typically this will only occur if the client specifies too many `DropCaps` such that the remaining width (to the right of the DropCap) is less than the size of one character of copy text.
Single DropCap | Two DropCaps
---|---
Lots of DropCaps | Not enough room for copy
---|---
> DropCap/ Allow multiple DropCaps

- drop-cap/library/src/main/java/com/novoda/dropcap/DropCapView.java
- drop-cap/sample/src/main/res/values/drop-cap-dimens.xml
`DropCapView` ignores padding rules even when a padding is supplied. When creating the `StaticLayouts` the `DropCapView` was using `totalWidth` rather than the `allowedWidth` which is the `totalWidth - horizonalPadding`.
Use `allowedWidth` for creation of all `StaticLayouts`.
Before | After
--- | ---
> DropCap/ Padding ignored

- TelepresenceBot/mobile/src/main/AndroidManifest.xml
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/bot/AndroidMovementService.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/bot/BotActivity.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/bot/MovementService.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/bot/MovementServiceIntentHandler.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/bot/SerialPortCreator.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/bot/SerialPortMonitor.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/bot/SupportedDeviceRetriever.java
- TelepresenceBot/mobile/src/main/java/com/novoda/tpbot/bot/UsbReceiver.java
- TelepresenceBot/mobile/src/test/java/com/novoda/tpbot/bot/MovementServiceIntentHandlerTest.java
- TelepresenceBot/mobile/src/test/java/com/novoda/tpbot/bot/SerialPortMonitorTest.java
- TelepresenceBot/mobile/src/test/java/com/novoda/tpbot/bot/SupportedDeviceRetrieverTest.java
In order for the `Bot` to work completely in the background, we need to move the `MovementService` to be a bound service that is destroyed in `onDestroy`. Unfortunately, I don't know how the `MovementService` works 😆 
Pull out testable collaborators for the `MovementService` and test them! In a follow-up PR we should be able to move everything to be in a bound service where the `BotService` forwards commands it receives to this `Service` 😄
> Tpbot/ Testable Movement Service

- piano-hero/mobile/src/main/java/com/novoda/pianohero/AndroidThingsActivity.java
- piano-hero/mobile/src/main/java/com/novoda/pianohero/MidiKeyboardDriver.java
- piano-hero/mobile/src/main/java/com/novoda/pianohero/NotesPlayedDispatcher.java
- piano-hero/mobile/src/main/java/com/novoda/pianohero/PianoC4ToB5Activity.java
- piano-hero/mobile/src/main/java/com/novoda/pianohero/SimpleUsbMidiDriver.java
This PR modifies the `KeyStationMini32` class to use `NoteListener` as a callback instead of `KeyListener` so we can plug it into `PianoC3ToB5Activity` to test if the game works.
It pulls out a `SimpleUsbMidiDriver` because it has so many unused methods too. It seems the driver doesn't work when you use it on a regular Android device to connect a digital piano - perhaps we'd have to check the MIDI feature thing and use the normal android feature where available, and the USB one otherwise.
> [piano-hero] Replace KeyListener with NoteListener and plug midi support into Piano...Activity

- espresso-support/README.md
- espresso-support/core/src/main/java/com/novoda/espresso/ViewTestRule.java
- espresso-support/demo/src/androidTest/java/com/novoda/movies/MovieItemViewTalkBackTest.java
- espresso-support/demo/src/androidTest/java/com/novoda/movies/MovieItemViewTest.java
View binding happens on a different thread to test execution, so tests aren't waiting for the binding to complete.
This can mean that test asserts are executed before binding is complete which is especially an issue when verifying method calls on a mock.
Implement Espresso's IdlingResource so we can block while view binding takes place.
@ataulm
> [espresso-support] Add idling resource

- espresso-support/README.md
- espresso-support/core/src/main/java/com/novoda/espresso/ViewTestRule.java
- espresso-support/demo/src/androidTest/java/com/novoda/movies/MovieItemViewTalkBackTest.java
- espresso-support/demo/src/androidTest/java/com/novoda/movies/MovieItemViewTest.java
We started using this method to do things that weren't just binding to the view and realised the name is very prescriptive.
Make it generic!
> [espresso-support] Rename bindViewUsing to runOnUiThread

- espresso-support/README.md
- espresso-support/core/src/main/java/com/novoda/espresso/ViewTestRule.java
- espresso-support/demo/src/androidTest/java/com/novoda/movies/MovieItemViewTalkBackTest.java
- espresso-support/demo/src/androidTest/java/com/novoda/movies/MovieItemViewTest.java
Hastily implemented IdlingResource to ViewTestRule.bind method to make tests wait for the bind to complete before moving on.
Unfortunately, this doesn't stop lines in the tests from executing - I suppose there's specific methods that respect the idling resource.
In any case, the binding of a view is not really a "resource". It turns out there's another method available on `Instrumentation` which allows you to run methods on the main thread (necessary if we want to bind views!) and here is the comment above:
```java
/**
* Execute a call on the application's main thread, blocking until it is
* complete.  Useful for doing things that are not thread-safe, such as
* looking at or modifying the view hierarchy.
* 
* @param runner The code to run on the main thread.
*/
public void …
```
> [espresso-support] Replace IdlingResource on ViewTestRule with Instrumentation.runOnMainSync

- espresso-support/build.gradle
- espresso-support/core/src/main/java/com/novoda/espresso/ViewTestRule.java
- espresso-support/dependencies.gradle
Fixes #323 
Updated dependencies to 3.0.1 version of Espresso and corresponding 1.0.1 of the test runner. Made the very small change needed to create the Intent rather than letting the superclass create it, which it no longer does (returns null).
Reran all the tests as per the README.
> Update for Espresso 3.0.1

- AlexaSpaceQuiz/lambda/custom/question.js
- AlexaSpaceQuiz/models/en-GB.json
Because otherwise it sounds wrong (it was reading the follow-up and immediately afterwards your score, without any pause inbetween)
Also adds English UK model
> [Space Quiz] Add dots at the end of follow up sentences

- game-of-life-multiplatform/common-js/build.gradle
- game-of-life-multiplatform/common-js/src/main/kotlin/com/novoda/gol/GameLoop.kt
- game-of-life-multiplatform/common-jvm/build.gradle
- game-of-life-multiplatform/common-jvm/src/main/kotlin/com/novoda/gol/GameLoop.kt
- game-of-life-multiplatform/common/build.gradle
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/GameLoopImpl.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/presentation/AppModel.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/presentation/AppPresenter.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/presentation/BoardModelImpl.kt
- game-of-life-multiplatform/common/src/main/kotlin/com/novoda/gol/presentation/BoardPresenter.kt
- game-of-life-multiplatform/common/src/test/kotlin/com/novoda/gol/presentation/AppPresenterTest.kt
- game-of-life-multiplatform/common/src/test/kotlin/com/novoda/gol/presentation/BoardPresenterTest.kt
- game-of-life-multiplatform/web/src/main/js/index.js
This PR introduces tests for Presenters and business logic of the game. 
- `GameLoop` is extracted as an interface to be able to have a stub implementation in the test. 
- `mockk` library is used because it is the only mocking framework with kotlin-multiplatform support. (I mean the first one we found)
PS: These tests were written first. We just didn't committed them until now. 
> Paired with @tobiasheine
> [GoL] Tests for business logic in common module

- game-of-life-multiplatform/android/src/main/java/com/novoda/gol/presentation/AndroidBoardView.kt
Rendering the CellView is done on the background thread leading to a crash. 
Ensuring rendering is done on the main thread fixes this.
**Steps to reproduce:**
Launch Android app
Choose blinker pattern
Click "Start Simulation"
-> Crash
**Stacktrace:**
```
02-01 23:09:18.122  3526  3544 W System.err: io.reactivex.exceptions.OnErrorNotImplementedException: Only the original thread that created a view hierarchy can touch its views.
02-01 23:09:18.122  3526  3544 W System.err: 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
02-01 23:09:18.122  3526  3544 W System.err: 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
02-01 23:09:18.122  3526  3544 W System.err: 	at …
```
> Prevent crash by ensuring rendering is done on the UI thread

- game-of-life-multiplatform/gradle.properties
- game-of-life-multiplatform/ios/build.gradle
Update Kotlin/Native 0.6.1 which finally enables debugging kotlin code using `lldb` 🎉 
For example:
`breakpoint set --file AppPresenter.kt --line 12`
> [Kotlin/Native] Upgrade Kotlin native 0.6.1

- dungeon-crawler/android/src/main/java/com/novoda/dungeoncrawler/DungeonCrawlerGame.java
- dungeon-crawler/android_things/src/main/java/com/novoda/dungeoncrawler/Apa102Display.java
- dungeon-crawler/android_things/src/main/java/com/novoda/dungeoncrawler/MainActivity.java
- dungeon-crawler/game_engine/src/main/java/com/novoda/dungeoncrawler/GameEngine.java
Introduces a few bugfixes:
- Fix `ArrayIndexOutOfBoundsException` when accessing the LED array
- Fix the Boss not drawing correctly
- Apply scale to LEDs, not sure if this is correct 🤔 
- Fix LED colour order (we were using GBR but the correct one is BGR)
- Change the `ATTACK_DURATION` to 700 millis. this feels better now as the player doesn't move as much after an attack (so it's easier to control)
- Move boss drawing code to the correct place (where we draw everything else)
> [dungeon crawler] Bugfixes

- dungeon-crawler/game_engine/src/main/java/com/novoda/dungeoncrawler/GameEngine.java
> [dungeon crawler] Fix the player only being able to move in one direction

- microservices-swift/Makefile
- microservices-swift/Package.resolved
This Makefile facilitates building and running artifacts that can be deployed in Linux machines. 
Examples: 
Run the server on a docker runtime image based on linux. 
```
$ make run_on_docker
```
Just create the linux artifact
```
$ make build_on_docker
```
> [SSS] Makefile for build and run commands
